### ISSUE TITLE
How do I make my home PC node visible to ergonode-spyder?

### ISSUE THREAD

**Issue by DellaRoccaD** [chriswill/ergonode-spyder#6]
I just finished syncing the Ergo Node/Wallet on one of my home PCs.  How would I go about making my node visible to ergonode-spyder?  Thank you.

**Comment by chriswill** [comment]
As mentioned on [this page](https://ergo.nodespyder.io/about), the spyder will only include nodes that it can connect to directly via P2P messages.  So, while the spyder will likely learn about your node if it shows up in the peer list of other nodes, it won't likely attempt a handshake connection to your node unless you've opened some type of public access through your home network.

**Comment by DellaRoccaD** [comment]
Thanks for the quick reply.  I was hoping I could make it visible somehow, perhaps by port forwarding port 9053 from my PC with the Ergo node.  If there is a way, it may be beneficial to describe the process on your website for regular non-IT professionals like myself.  Website looks really good, just conveys a potentially negative message showing so few nodes...
